# Cloud Build configuration for Inmuebles App
steps:
  # Build Ollama service
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-ollama'
    args: 
      - 'build'
      - '-f'
      - 'Dockerfile.ollama'
      - '-t'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/inmuebles-app/ollama-service:latest'
      - '.'
  
  # Build Streamlit service
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-streamlit'
    args: 
      - 'build'
      - '-f'
      - 'Dockerfile.streamlit'
      - '-t'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/inmuebles-app/streamlit-app:latest'
      - '.'
  
  # Push Ollama image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-ollama'
    args: 
      - 'push'
      - '--all-tags'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/inmuebles-app/ollama-service'
    waitFor: ['build-ollama']
  
  # Push Streamlit image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-streamlit'
    args: 
      - 'push'
      - '--all-tags'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/inmuebles-app/streamlit-app'
    waitFor: ['build-streamlit']
  
  # Deploy Ollama service
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-ollama'
    args:
      - 'run'
      - 'deploy'
      - 'ollama-service'
      - '--image'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/inmuebles-app/ollama-service:latest'
      - '--port'
      - '8080'
      - '--concurrency'
      - '4'
      - '--cpu'
      - '4'
      - '--set-env-vars'
      - 'OLLAMA_NUM_PARALLEL=4'
      - '--max-instances'
      - '1'
      - '--memory'
      - '8Gi'
      - '--region'
      - 'us-east1'
      - '--allow-unauthenticated'
      - '--no-cpu-throttling'
      - '--timeout'
      - '1800'
    waitFor: ['push-ollama']
  
  # Deploy Streamlit service (after Ollama is deployed)
  # Step 1: Get Ollama URL and store it
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'get-ollama-url'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        OLLAMA_URL=$$(gcloud run services describe ollama-service --region=us-east1 --format="value(status.url)")
        echo "OLLAMA_HOST=$$OLLAMA_URL" > /workspace/ollama-url.env
        echo "Ollama URL: $$OLLAMA_URL"
    waitFor: ['deploy-ollama']

  # Step 2: Deploy Streamlit with environment variables
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-streamlit'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/ollama-url.env
        QDRANT_HOST=$$(gcloud secrets versions access latest --secret=QDRANT_HOST)
        QDRANT_API_KEY=$$(gcloud secrets versions access latest --secret=QDRANT_API_KEY)
        
        gcloud run deploy streamlit-app \
          --image us-east1-docker.pkg.dev/$PROJECT_ID/inmuebles-app/streamlit-app:latest \
          --memory 2Gi \
          --cpu 1 \
          --port 8080 \
          --timeout 300 \
          --allow-unauthenticated \
          --region us-east1 \
          --set-env-vars "OLLAMA_HOST=$$OLLAMA_HOST,QDRANT_HOST=$$QDRANT_HOST,QDRANT_API_KEY=$$QDRANT_API_KEY"
    waitFor: ['push-streamlit', 'get-ollama-url']

# Store images in Artifact Registry
images:
  - 'us-east1-docker.pkg.dev/$PROJECT_ID/inmuebles-app/ollama-service:latest'
  - 'us-east1-docker.pkg.dev/$PROJECT_ID/inmuebles-app/streamlit-app:latest'

# Build options
# options:
#   machineType: 'E2_HIGHCPU_8'  # Faster builds
#   logging: CLOUD_LOGGING_ONLY
