services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - LOCAL=false
      - MLFLOW_TRACKING_URI=file:///app/mlruns
    volumes:
      - ./mlruns:/app/mlruns # Mount models
    restart: always
